### ISSUE TITLE
Fails to statify ELF 64-bit LSB executable, x86-64, version 1 (SYSV)

### ISSUE THREAD

**Issue by Semnodime** [sigurd-dev/mkblob#1]
`mkblob ./mybin -o blob`
->
`./mybin does not seem to be an executable file.`

----

`file ./mybin`
->
`./mybin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=<xxxxhiddenxxxx>, stripped`

**Comment by sigurd-dev** [comment]
Try giving full path to mybin.
Usage: mkblob /full/path/to/mybin -o blob
