### ISSUE TITLE
Uncaught exception: Couldn't create SDL window?

### ISSUE THREAD

**Issue by jpenguin** [sigurd-dev/mkblob#2]
I'm really new to linux packaging.  I compiled https://github.com/jorio/Bugdom on Tumbleweed, ran `mkblob /home/tuxpeng/Bugdom/build-release/Bugdom -o Bugdom.static -static`  The result ran great on the host system.  Then I tried the binary on a Ubuntu 20.04 VM 
> Uncaught exception: Couldn't create SDL window

So, I tried compiling o n Ubuntu and running on Tumbleweed, same error.  Is there any way to make this work?

Build from OpenSUSE: https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Bugdom/Bugdom.tar.gz

**Comment by sigurd-dev** [comment]
You can try this in a terminal on your VM:
export SDL_VIDEO_X11_VISUALID= 
./Bugdom.static

Ref.: https://github.com/opentomb/OpenTomb/issues/561

BTW, it works nice in CentOS 7

**Comment by jpenguin** [comment]
THx, just a=something about *buntu; it gets further, but still complain about vertex shaders.  SDL2 is the only depend, I'll just mention on Lutris it needs to be installed
